// Date: 10/2/2014 9:51:47 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelLazer extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer LeftBox;
    ModelRenderer RightBox;
    ModelRenderer Light;
    ModelRenderer GlassTop;
  
  public ModelLazer()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Base = new ModelRenderer(this, 0, 15);
      Base.addBox(-4F, -2F, -4F, 8, 3, 8);
      Base.setRotationPoint(0F, 23F, 0F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      LeftBox.mirror = true;
      LeftBox = new ModelRenderer(this, 28, 0);
      LeftBox.addBox(3F, -3F, -1F, 2, 4, 2);
      LeftBox.setRotationPoint(0F, 23F, 0F);
      LeftBox.setTextureSize(64, 32);
      LeftBox.mirror = true;
      setRotation(LeftBox, 0F, 0F, 0F);
      LeftBox.mirror = false;
      RightBox = new ModelRenderer(this, 28, 0);
      RightBox.addBox(-5F, -3F, -1F, 2, 4, 2);
      RightBox.setRotationPoint(0F, 23F, 0F);
      RightBox.setTextureSize(64, 32);
      RightBox.mirror = true;
      setRotation(RightBox, 0F, 0F, 0F);
      Light = new ModelRenderer(this, 28, 6);
      Light.addBox(-2F, -6F, -2F, 3, 4, 3);
      Light.setRotationPoint(0.5F, 23F, 0.5F);
      Light.setTextureSize(64, 32);
      Light.mirror = true;
      setRotation(Light, 0F, 0F, 0F);
      GlassTop = new ModelRenderer(this, 0, 0);
      GlassTop.addBox(-4F, -10F, -4F, 7, 8, 7);
      GlassTop.setRotationPoint(0.5F, 23F, 0.5F);
      GlassTop.setTextureSize(64, 32);
      GlassTop.mirror = true;
      setRotation(GlassTop, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Base.render(f5);
    LeftBox.render(f5);
    RightBox.render(f5);
    Light.render(f5);
    GlassTop.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
