// Date: 7/22/2014 8:30:48 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelRecordEtcher extends ModelBase
{
  //fields
    ModelRenderer case;
    ModelRenderer holder;
    ModelRenderer frontLeftPeg;
    ModelRenderer backRightPeg;
    ModelRenderer backLeftPeg;
    ModelRenderer frontRightPeg;
    ModelRenderer top;
    ModelRenderer topCase;
    ModelRenderer etcher;
  
  public ModelRecordEtcher()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      case = new ModelRenderer(this, 0, 0);
      case.addBox(-7F, 0F, -7F, 14, 10, 14);
      case.setRotationPoint(0F, 14F, 0F);
      case.setTextureSize(64, 64);
      case.mirror = true;
      setRotation(case, 0F, 0F, 0F);
      holder = new ModelRenderer(this, 0, 4);
      holder.addBox(-0.5F, -1F, -0.5F, 1, 1, 1);
      holder.setRotationPoint(0F, 14F, 0F);
      holder.setTextureSize(64, 64);
      holder.mirror = true;
      setRotation(holder, 0F, 0F, 0F);
      frontLeftPeg.mirror = true;
      frontLeftPeg = new ModelRenderer(this, 0, 0);
      frontLeftPeg.addBox(6F, -3F, -7F, 1, 3, 1);
      frontLeftPeg.setRotationPoint(0F, 14F, 0F);
      frontLeftPeg.setTextureSize(64, 64);
      frontLeftPeg.mirror = true;
      setRotation(frontLeftPeg, 0F, 0F, 0F);
      frontLeftPeg.mirror = false;
      backRightPeg = new ModelRenderer(this, 0, 0);
      backRightPeg.addBox(-7F, -3F, 6F, 1, 3, 1);
      backRightPeg.setRotationPoint(0F, 14F, 0F);
      backRightPeg.setTextureSize(64, 64);
      backRightPeg.mirror = true;
      setRotation(backRightPeg, 0F, 0F, 0F);
      backLeftPeg.mirror = true;
      backLeftPeg = new ModelRenderer(this, 0, 0);
      backLeftPeg.addBox(6F, -3F, 6F, 1, 3, 1);
      backLeftPeg.setRotationPoint(0F, 14F, 0F);
      backLeftPeg.setTextureSize(64, 64);
      backLeftPeg.mirror = true;
      setRotation(backLeftPeg, 0F, 0F, 0F);
      backLeftPeg.mirror = false;
      frontRightPeg = new ModelRenderer(this, 0, 0);
      frontRightPeg.addBox(-7F, -3F, -7F, 1, 3, 1);
      frontRightPeg.setRotationPoint(0F, 14F, 0F);
      frontRightPeg.setTextureSize(64, 64);
      frontRightPeg.mirror = true;
      setRotation(frontRightPeg, 0F, 0F, 0F);
      top = new ModelRenderer(this, 0, 24);
      top.addBox(-7F, -4F, -7F, 14, 1, 14);
      top.setRotationPoint(0F, 14F, 0F);
      top.setTextureSize(64, 64);
      top.mirror = true;
      setRotation(top, 0F, 0F, 0F);
      topCase = new ModelRenderer(this, 0, 39);
      topCase.addBox(-4F, -5F, -4F, 8, 1, 8);
      topCase.setRotationPoint(0F, 14F, 0F);
      topCase.setTextureSize(64, 64);
      topCase.mirror = true;
      setRotation(topCase, 0F, 0F, 0F);
      etcher = new ModelRenderer(this, 0, 39);
      etcher.addBox(-0.5F, -5F, -0.5F, 1, 3, 1);
      etcher.setRotationPoint(0F, 14F, 0F);
      etcher.setTextureSize(64, 64);
      etcher.mirror = true;
      setRotation(etcher, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    case.render(f5);
    holder.render(f5);
    frontLeftPeg.render(f5);
    backRightPeg.render(f5);
    backLeftPeg.render(f5);
    frontRightPeg.render(f5);
    top.render(f5);
    topCase.render(f5);
    etcher.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
